[project]
name = "myproject"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
cowpy = "1.1.5.*"
python = "3.10.*"
pymc = "5.9.0.*"
causalpy = "0.1.2.*"
pandas = "2.1.1.*"
ipykernel = "6.25.2.*"
scikit-learn = "1.3.1.*"
plotly = "5.17.0.*"
bambi = "0.13.0.*"
ipyleaflet = "0.17.4.*"
jupyterlab = "4.0.6.*"
geopandas = "0.14.0.*"
geodatasets = "2023.3.0.*"
httpx = "0.25.0.*"
sweetviz = "2.2.1.*"
